# -*- coding: utf-8 -*-
"""model_execution

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MZvhVdVtj9N0I_AUk_BMqM1MnX0jt-SI
"""

# Mount Google Drive
from google.colab import drive
drive.mount('/content/drive')

# Load model from Drive (correct path to .h5 file)
from tensorflow.keras.models import load_model
model = load_model('/content/drive/MyDrive/panda_bear_classifier.h5')
print("Model loaded from Google Drive!")

# Upload images to predict
from google.colab import files
uploaded = files.upload()

# Predict and visualize
from tensorflow.keras.preprocessing import image
import numpy as np
import matplotlib.pyplot as plt

IMG_SIZE = (150, 150)
class_names = ['Bear', 'Panda']

for img_name in uploaded.keys():
    img = image.load_img(img_name, target_size=IMG_SIZE)
    img_array = image.img_to_array(img) / 255.0
    img_array = np.expand_dims(img_array, axis=0)

    pred = model.predict(img_array)[0][0]
    label_index = int(pred > 0.5)
    label = class_names[label_index]
    confidence = pred if label_index == 1 else 1 - pred

    plt.imshow(img)
    plt.axis('off')
    plt.title(f"{img_name}\nPrediction: {label} ({confidence*100:.2f}% confidence)")
    plt.show()